name: Build & Push Docker

on:
  push:
  Workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: alysialfi/notification-page
          tags: v1, latest
          registry: docker.io
          dockerfile: docker/DockerFile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}