name: My First Workflow Github actions/checkout batch September

on:
  push:

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World"

