name: Testing Workflow

on:
  push:
  Workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v4
      - name: install package
        run: npm i
      - name: run test cases
        run: npm run test