name: Testing Workflow (Batch September)

on:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: install package
        run: npm i
      - name: run test cases
        run: npm run test